[package]
name = "interpreter"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
clap = { version = "4.5.20", features = ["derive"] }
derive_more = { version = "1.0.0", features = ["display"] }
strum = "0.26.3"
strum_macros = "0.26.4"
thiserror = "1.0.65"
